version: "3.9"

services:
  eduky-monitor:
    build: 
      context: ../..
      dockerfile: scripts/docker/Dockerfile
    image: ghcr.io/eduky/eduky-monitor:latest
    container_name: eduky-monitor
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=${FLASK_ENV:-production}
      - TZ=${TZ:-UTC}
    volumes:
      - eduky_data:/opt/eduky-monitor/web/instance
      - eduky_logs:/opt/eduky-monitor/logs
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - eduky-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp

  # 可选：添加反向代理
  nginx:
    image: nginx:alpine
    container_name: eduky-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      eduky-monitor:
        condition: service_healthy
    networks:
      - eduky-network
    profiles:
      - with-nginx

  # 可选：添加数据库备份服务
  backup:
    image: alpine:latest
    container_name: eduky-backup
    restart: "no"
    volumes:
      - eduky_data:/data:ro
      - ./backups:/backups
    command: |
      sh -c "
        apk add --no-cache tar gzip &&
        tar -czf /backups/eduky-backup-$$(date +%Y%m%d_%H%M%S).tar.gz -C /data . &&
        find /backups -name '*.tar.gz' -mtime +7 -delete
      "
    networks:
      - eduky-network
    profiles:
      - backup

volumes:
  eduky_data:
    driver: local
  eduky_logs:
    driver: local
  nginx_cache:
    driver: local

networks:
  eduky-network:
    driver: bridge